version: "3.8"
services:
  musicblocks:
    build: ./
    image: musicblocks:initial
    ports:
      - "5000:80"
    volumes:
      - ./:/app/
    container_name: musicblocks
    stdin_open: true
    tty: true
