---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Super-Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout the code base
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ####################
      # Run Super Linter #
      ####################
      - name: Lint new and edited files
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: develop
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc
          MARKDOWN_CONFIG_FILE: .markdownlint.jsonc
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
